root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/server ./cmd/api"
  delay = 200
  stop_on_error = true
  send_interrupt = true
  kill_delay = "500ms"
  exclude_unchanged = true
  bin = "tmp/server"
  include_ext = ["go", "mod"]
  exclude_dir = ["tmp", "vendor"]

[log]
  time = true